@startuml classes
set namespaceSeparator none
interface "IAssetsCollector" as interfaces.modules.IAssetsCollector {
  assets
  rom_collector_dto
  {abstract}run() -> None
}
interface "ICommand" as interfaces.commands.ICommand {
  {abstract}execute() -> None
}
interface "IGenericContainerEngine" as interfaces.engines.IGenericContainerEngine {
  builder_cmd
  container_options
  dir_bundle_conan
  get_container_cmd
  {abstract}build_image() -> str | None | CompletedProcess
  {abstract}check_cache() -> bool
  {abstract}create_dirs() -> None
}
interface "IKernelBuilder" as interfaces.modules.IKernelBuilder {
  {abstract}build() -> None
  {abstract}clean_build() -> None
  {abstract}create_zip() -> None
  {abstract}patch_all() -> None
  {abstract}patch_anykernel3() -> None
  {abstract}patch_ioctl() -> None
  {abstract}patch_kernel() -> None
  {abstract}patch_ksu() -> None
  {abstract}patch_qcacld() -> None
  {abstract}patch_rtl8812au() -> None
  {abstract}patch_rtl8812au_source_mod_v5642() -> None
  {abstract}patch_strict_prototypes() -> None
  {abstract}run() -> None
  {abstract}update_defconfig() -> None
  {abstract}write_localversion() -> None
}
interface "IResourceManager" as interfaces.managers.IResourceManager {
  {abstract}download() -> None
  {abstract}export_path() -> None
  {abstract}generate_paths() -> None
  {abstract}read_data() -> None
}
interface "IRomApiClient" as interfaces.clients.IRomApiClient {
  {abstract}map_codename() -> str
  {abstract}run() -> str
}
@enduml
