@startuml classes
set namespaceSeparator none
class "AssetsCommand" as commands.assets.AssetsCommand {
  assets_collector : AssetsCollector
  execute() -> None
}
class "BundleCommand" as commands.bundle.BundleCommand {
  assets_collector : AssetsCollector
  kernel_builder : KernelBuilder
  package_type : str
  build_kernel(rom_name: str, clean_only: Optional[bool]) -> None
  collect_assets(rom_name: str, chroot: Literal['full', 'minimal']) -> None
  conan_options(json_file: str) -> dict
  conan_package(options: tuple[str, ...], reference: str) -> None
  conan_sources() -> None
  conan_upload(reference: str) -> None
  execute() -> None
}
class "KernelCommand" as commands.kernel.KernelCommand {
  kernel_builder : KernelBuilder
  execute() -> None
}
@enduml
