@startuml classes
set namespaceSeparator none
class "AssetsCommand" as commands.assets.AssetsCommand {
  base : str
  chroot : Literal['full', 'minimal']
  clean_assets : bool
  codename : str
  ksu : bool
  rom_only : bool
  execute() -> None
}
class "BundleCommand" as commands.bundle.BundleCommand {
  base : str
  codename : str
  defconfig : Optional[Path]
  ksu : bool
  lkv : str
  package_type : str
  build_kernel(rom_name: str, clean_only: bool) -> None
  collect_assets(rom_name: str, chroot: Literal['full', 'minimal']) -> None
  conan_options(json_file: str) -> dict
  conan_package(options: tuple[str, ...], reference: str) -> None
  conan_sources() -> None
  conan_upload(reference: str) -> None
  execute() -> None
}
class "KernelCommand" as commands.kernel.KernelCommand {
  base : str
  clean_kernel : bool
  codename : str
  defconfig : Optional[Path]
  ksu : bool
  lkv : str
  execute() -> None
}
@enduml
