@startuml packages
set namespaceSeparator none
package "tools" as tools {
}
package "tools.cleaning" as tools.cleaning {
}
package "tools.commands" as tools.commands {
}
package "tools.fileoperations" as tools.fileoperations {
}
package "tools.messages" as tools.messages {
}
@enduml
