@startuml classes
set namespaceSeparator none
class "GithubApiClient" as clients.github.GithubApiClient {
  direct_url
  endpoint
  file_filter : Optional[str]
  project : str
  run() -> str | None
}
class "LineageOsApiClient" as clients.los.LineageOsApiClient {
  endpoint : str
  json_key : str
  rom_name : str
}
class "ParanoidAndroidApiClient" as clients.pa.ParanoidAndroidApiClient {
  endpoint : str
  json_key : str
  rom_name : str
  codename_mapper() -> str
}
class "RomApiClient" as clients.rom_api.RomApiClient {
  codename : str
  endpoint : str
  json_key : str
  rom_name : str
  rom_only : bool
  codename_mapper() -> str
  run() -> str
}
@enduml
