@startuml classes
set namespaceSeparator none
class "ArgumentConfig" as configs.argument.ArgumentConfig {
  base : str
  benv : Literal['docker', 'podman', 'local']
  chroot : Optional[str]
  clean_assets : bool
  clean_image : bool
  clean_kernel : bool
  codename : str
  command : Literal['kernel', 'assets', 'bundle']
  conan_upload : bool
  defconfig : Optional[Path]
  ksu : bool
  lkv : Optional[str]
  package_type : Optional[str]
  rom_only : bool
  check_settings() -> None
}
class "DirectoryConfig" as configs.directory.DirectoryConfig {
  assets : Path
  bundle : Path
  kernel : Path
  root : Path
}
@enduml
