@startuml classes
set namespaceSeparator none
class "GenericContainerEngine" as engines.generic_container.GenericContainerEngine {
  base : str
  benv : Literal['docker', 'podman']
  builder_cmd
  chroot : Optional[Literal['full', 'minimal']]
  clean_assets : Optional[bool]
  clean_image : Optional[bool]
  clean_kernel : Optional[bool]
  codename : str
  command : Literal['kernel', 'assets', 'bundle']
  conan_upload : Optional[bool]
  container_options
  dir_bundle_conan
  ksu : Optional[bool]
  lkv : Optional[str]
  package_type : Optional[str]
  rom_only : Optional[bool]
  run_cmd
  build_image() -> str | None | CompletedProcess
  check_cache() -> bool
  create_dirs() -> None
}
@enduml
